### ISSUE TITLE
What's the progress on this project?

### ISSUE THREAD

**Issue by IonicaBizau** [NodeOS/NodeOS#110]
I remembered this project... What's the progress on it?

Is there graphical interface to test? Where can I find the roadmap and the current progress?

Thanks! :smile:

**Comment by piranna** [comment]
Hi @IonicaBizau, NodeOS is moving forward, but it's slow because we have very few man-power and it's done on our spare time :-) We don't have graphical interface yet but @netlovers got [huge improvements](https://github.com/NodeOS/NodeOS/issues/79), but for the alpha release [we are going to focus on a server-only OS](https://github.com/NodeOS/NodeOS/issues/37).

Our main focus at this moment is to get a stable and secure file hierarchy that would give the impression the user is the owner of all the computer, using extensively file permissions, OverlayFS mount points and maybe LXC containers to give this feeling to the final user.

**Comment by IonicaBizau** [comment]
Cool! Thanks for reply. Keep up the good work! :+1:
