### ISSUE TITLE
Do you have any plan to make the OS run on ARM/Mobile as well ?

### ISSUE THREAD

**Issue by meepeek** [NodeOS/NodeOS#114]

**Comment by piranna** [comment]
It's on roadmap to port it to Raspberry Pi that's ARM based, but there are some compilation problems (maybe bad generation of the cross-toolchain?). You can try it yourself with "PLATFORM=raspberry npm install", any help here is welcome since I never used ARM before.

**Comment by netlovers** [comment]
io.js added ARM support a few days ago:
https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#2015-03-02-version-143-rvagg
So maybe node.js does not even support it at the moment?

**Comment by piranna** [comment]
That's support for recent ARM versions (armv8 and ARM 64 bits). Node.js has build-in support for ARM since long ago and there are pre-build binaries specific for Raspberry Pi, and some work towards MIPS and PowerPC (old Macintosh, or GameCube and Wii). The compilation problems were related to Linux kernel :-/

**Comment by piranna** [comment]
Ah, and PS3 and XBox 360 has a three core PowerPC chip, too :-P

**Comment by meepeek** [comment]
Thanks for quick answer.

**Comment by piranna** [comment]
You are welcome :-)
