### ISSUE TITLE
What about developing environment for developers?

### ISSUE THREAD

**Issue by csrgxtu** [NodeOS/NodeOS#119]
I am just wondering if NodeOS contains developer environments for programmers, like vim, gcc shell and so on?

**Comment by eush77** [comment]
Why would you need gcc on NodeOS? There is a [clang port](https://github.com/kripken/clangor) and [llvm.js](https://github.com/kripken/llvm.js), but what would gcc do?

**Comment by csrgxtu** [comment]
cause since it is an os, so i think if it is user friendly as Ubuntu or can i use it as my linux box as i use everyday.

**Comment by piranna** [comment]
NodeOS aims to be as minimalistic as possible, delegating all extra functionality to user installed npm packages, so no, it will not have a developing environment by itself. On the other hand, you can use [slap](https://github.com/slap-editor/slap) as IDE text editor, and as @eush77 said there are LLVM ports to Javascript.

In any case at this moment NodeOS is in pre-alpha status, so I don't think is ready for an everyday use, but when we re-enable network support, it could be used as a server in production...

**Comment by derhuerst** [comment]
Actually, i think that NodeOS is not suited at all for day-to-day programming work. Porting all the Compiler, LLVM, build and shell stuff is is like reinventing the wheel, just because it's possible.

In contrast, what NodeOS its perfect for is hosting small node-only applications and powering small boards for internet of things / tinkering stuff.
