### ISSUE TITLE
Installing Node OS on Raspberry Pi

### ISSUE THREAD

**Issue by d0nd3r3k** [NodeOS/NodeOS#12]
It's really complex at this time to install Docker on RaspberryPi, is it possible to install Node OS on the Raspberry Pi without Docker ?

**Comment by sivatumma** [comment]
@groundwater, What is the current picture on this view... I am eager to know.

**Comment by piranna** [comment]
Cross-compile needs some improvements, but it should work. Unluckily I was not able to test it because I don't have a RPI 2 or RPi 3. Latests changes in QEmu seem now it would be possible to test it too, but didn't have time. Alternatively, it would be a nice addition to add support for other toolchains...
