### ISSUE TITLE
fundamental question: is Node-os is lfs(linux from scratch) ,based on distro or even an abstraction layer?

### ISSUE THREAD

**Issue by bbsalsero** [NodeOS/NodeOS#122]
every thing is in the title,

is Node-os a full lfs ,based on distro or even an abstraction layer?

**Comment by piranna** [comment]
I don't understand what you want to know. What's a lfs?

**Comment by bbsalsero** [comment]
sorry for the misunderstanding, lfs mean linux from scratch.

**Comment by piranna** [comment]
Ah, ok. No, NodeOS is not based on any distro nor it's an abstraction layer, it's an standalone Linux-based OS that use Node.js as runtime instead of GNU, similar in some way to Android or ChromeOS or FirefoxOS. It use Linux from Scratch as a basis and inspiration (more exactly [clfs embedded](http://clfs.org/view/clfs-embedded/)) about how to do some things regarding to the build process, but it's not derived from it.
