### ISSUE TITLE
DNS is broken

### ISSUE THREAD

**Issue by secrettriangle** [NodeOS/NodeOS#144]
I ran `node -p "require('http').get('http://google.com').pipe(require('fs').createWriteStream('yo'))"` in NodeOS and got `EAI_AGAIN`.

**Comment by piranna** [comment]
Is correct the DNS server on the /etc/resolv.conf file? Also, I've reenabled network support last week and it's in very early state, please take a look at https://github.com/NodeOS/NodeOS/issues/137, I talk here about my progress and actual state.

**Comment by piranna** [comment]
By the way, thank you for testing it so thoroughtly! :-)

**Comment by secrettriangle** [comment]
Hmm, I'll try that out. Have you considered using Google's `8.8.8.8` and `8.8.4.4` or using the host's DNS?

**Comment by secrettriangle** [comment]
There's no `/etc/resolv.conf` on the latest build?

**Comment by piranna** [comment]
> Hmm, I'll try that out. Have you considered using Google's 8.8.8.8 and 8.8.4.4 or using the host's DNS?

At a first glance I tried Google DNSs but it was not working due to routing so I set the one of QEmu virtual LAN (that internally redirect requests to host DNS), but now that routing is working yes, we could use Google ones :-)


> There's no /etc/resolv.conf on the latest build?

It's on the [nodeos home folder](https://github.com/NodeOS/NodeOS/blob/master/node_modules/nodeos-usersfs/resolv.conf). Start forgetting about global files, everything will be on your $HOME folder on NodeOS ;-)

**Comment by piranna** [comment]
I've tried to use Google DNSs and it works correctly, it will be ready the next time I do ```git push```, so I'll close this issue. At this moment you need to enable by hand the network card and define the gateway, so next movement is to develop a ```/etc/network/interface```-like file or better use a DHCP client to make this step easier.
