### ISSUE TITLE
Fix networking in NodeOS

### ISSUE THREAD

**Issue by dbkaplun** [NodeOS/NodeOS#149]
Related: #144

I shouldn't have to do any manual steps to access the public internet from NodeOS after booting. Whether that means that a 'default' network interface is pre-created, or DHCP is implemented, it doesn't matter, as long as I can access `google.com` on startup.

**Comment by piranna** [comment]
Could you be able to describe what need to be fixed? As I said on the other issue, network is working again and the only problem is that you need to set the IP and the route by hand, no DHCP. Is this what you are talking about?

**Comment by secrettriangle** [comment]
I've updated the description. Hope that makes things clearer!

**Comment by piranna** [comment]
Ah, ok, much better! :-D Yes, I think we need a DHCP client enabled by default. I have been trying [dhcpjs](https://github.com/apaprocki/node-dhcpjs) but it's not working don't know why :-(

There are some issues and things that need to be fixed/discussed here regarding networking:

* there's only one (or very few) network cards on a system that need to be shared by all the users, and we don't have network isolation (at least until we use LXC containers). If we set one IP, this will be need to be done by root on startup and can't be changed, or someone will need to have administrator permissions, going against the philosofy of NodeOS
* we can set a DHCP client and fetch an IP and default gateway on startup, but what happens if people want to set a static IP? How to do it?

The only solution I think is to use a DHCP client by default and allow people to set their own IPs. Linux allow to have several IPs on a single network card, but this IPs need to be on the same address space of the external network and also I don't know how much difficult would be to add the virtual network cards dynamically and only allow to configure one for each user. Also, maybe in that case it would make more sense to have a private LAN on the host machine to connect the users and all of them going to internet through a gateway, similar to how QEmu emulated network works, but here we have NAT problems and so... :-/ What do you think?

**Comment by piranna** [comment]
http://superuser.com/questions/502793/how-to-bring-network-up-at-boot-time-in-linux
https://www.kernel.org/doc/Documentation/filesystems/nfs/nfsroot.txt

Ok, so Linux kernel allow to define the IP as a boot cmdline argument :-) It would neet to be tested, but this way a DHCP server could be started by default, and allow to set a static IP as a boot param :-)

**Comment by piranna** [comment]
NodeOS now uses DHCP on boot time and is capable of using npm to install packages, so clossing :-)
