### ISSUE TITLE
X graphics

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#178]
Hi! I've been watching the project for a little while. I've been experimenting trying to find a solution for our ever repeated graphic issue. While looking around, it dawned on me that we could use the X windowing system. I thought I'd bring it up. There seem to are already be nodejs bindings for the x windowing system. (see https://github.com/sidorares/node-x11) I have a bit of experience writing window managers and I believe we could create a complete graphical desktop environment using x11. Using x11 would allow non-js applications to run, and by writing the desktop environment in nodejs, users would have full control of how their desktop looked and operated. They could completely modify it, like all the other systems in the Os.

I'm anxious to hear your opinions! Have a great day.

**Comment by sidorares** [comment]
hi @lite20  - take a look at https://github.com/sidorares/ntk and https://github.com/sidorares/react-x11 , these are higher level wrappers on top of node-x11. No documentation yet and very much still WIP but I'm keen to continue developing them

**Comment by netlovers** [comment]
@piranna does not really like the idea of using X. I only checked it out once, but it seems like X has billions upon billions of dependencies, and you'll most likely need to include different graphics drivers too. But I think it would be great, if we could compile a minimal X, and make an optional build param in the NodeOS build script to use it.

**Comment by sidorares** [comment]
@GothAck is working on implementation of X server that works in the browser :)

https://github.com/GothAck/javascript-x-server

**Comment by netlovers** [comment]
Hmm, looks interesting, but it needs a browser to show the stuff that you want to render, so I guess this could be a remote only option, right?

**Comment by sidorares** [comment]
yes

"X has billions upon billions of dependencies" - that's not always the case. It could really be just a small single executable

**Comment by netlovers** [comment]
Do you have a build script ready for it? Because it would be really great, in my opinion.
There are two ways I could imagine this could go:
1) A super minimal X build, and we could use `node-x11` to render everything by ourselves.
2) Or an X build that only has the dependencies to be able to run a Chrome build, and basically Chrome would become the "window manager".

**Comment by sidorares** [comment]
no, but various distributions should have it. Full X server was even part of Nokia N900

**Comment by piranna** [comment]
First of all, interesting and collaborative issue, let's keep moving on! :-)

Ok, my opinion. From my point of view, NodeOS has more power as a server-only OS, but it's true people usually ask about having a GUI (and that's one of the reasons I ported node-canvas to the framebuffer). By using a web browser for the GUI frontend we can have a remote GUI, and oviously this web browser can be executed on the same machine where NodeOS is running, having a so called "native" GUI. Why a browser and not other thing like node-X11? Nothing special besides the fact that web browsers are easier to program, they are everywhere and that Node.js developers would be more familiar with them since it's HTML+Javascript :-) Also there's a problem with "native" GUIs, that's apps need to be ported between platform. By using pure web technologies (and not hybrid ones like nw.js) we can be sure to make it work everywhere and with network support by default.

As @netlovers told, I'm against X11 by several reasons:

* it's overcomplicated
* add several dependencies
* requires administrator priviledges and a central configuration (hope that someone wrongs me here)
* and more than this, that's another abstraction layer that decrease performance compared to other alternatives like DRI or EGL

This statement is not an absolute "NO!" but mostly an advice to the ones that want to do it. I think it would be better to start trying to build and pack a Chromium `content_shell` using DRI (framebuffer) as a npm package that anyone can launch himself (specially now that users have secure access to the devices, including framebuffer) and later try to accelerate it with EGL, so we could have no middle layers the same way as ChromeOS does and gain the best performance. Said that, if somebody manages to made NodeOS to start a X11-based web browser, I will be more than willingly to help him :-)

Anyway, in my opinion NodeOS should never have a GUI on it's core, and if so it should be an independent project that can also run on other OSes. This doesn't means I don't want NodeOS to have a desktop, and in fact I have been the last days thinking about it... :-D

![20151116_082823](https://cloud.githubusercontent.com/assets/532414/11188443/23768ece-8c8b-11e5-9a66-faf7968e4b97.jpg)

**Comment by lite20** [comment]
Oooh very fancy doodles! I've read some pretty enlightening things. I'm going to mess around with your framebuffer port and see if I can get an implementation of webkit or chrome to render to it. With the x11 process I did mean using x11 coupled with a browser like CEF. That would be baked right into said window manager.

This is my plan. I'll monitor the progress of https://github.com/GothAck/javascript-x-server and see if I can maybe contribute. I will also work to remove CEF's or webkit's render scripts and replace them with a framebuffer implementation. Hopefully someone with more EGL experience can join on that and help with the EGL implementation. 

Ideally, I would love to end up running NodeOS on a phone I've developed as a side project. I find NodeOS's hackability a beautiful feature that suits the phone perfectly. It's definitely a step from where we are now, but projects like these have no limits.

I really like those doodles by the way. Reminds me of the design sketches up in my bedroom.

**Comment by lite20** [comment]
Just as a side note, maybe it may be a good idea to create a second branch for the graphical edition of NodeOS since we want to keep them separated. That way the main branch can  remain dedicated to NodeOS server, free of graphic clutter, while NodeOS's graphic branch will expand on it. Just a suggestion :smile:

**Comment by piranna** [comment]
> Oooh very fancy doodles!

Thank you! ^^ They need some explains, but I think show the general idea I have in my mind :-)


> I'm going to mess around with your framebuffer port and see if I can get an implementation of webkit or chrome to render to it. With the x11 process I did mean using x11 coupled with a browser like CEF

Before wrong here: my [node-canvas port](https://github.com/NodeOS/node-canvas) is just only to paint on the screen from Node.js, it doesn't have anything about making CEF to run on it, but it was a good starting point.

Regarding content_shell on framebuffer (CEF is the full Chromium, while we are interested only on the rendering engine), I think it should be mostly a matter of following [this instructions](https://www.chromium.org/developers/design-documents/ozone) to compile the embebed version with the DRM platform. It will be software rendered, but would allow to move forward later for accelerated GBM platform, and later figure out how to increase the resolution from 800x600 to fullscreen. I think @netlovers or @formula1 achieved some progress on this area in the past...


> Ideally, I would love to end up running NodeOS on a phone I've developed as a side project. I find NodeOS's hackability a beautiful feature that suits the phone perfectly. It's definitely a step from where we are now, but projects like these have no limits.

That's a cool idea! Do you have somewhere some info about that phone you've build? :-)


> Just as a side note, maybe it may be a good idea to create a second branch for the graphical edition of NodeOS since we want to keep them separated. That way the main branch can remain dedicated to NodeOS server, free of graphic clutter, while NodeOS's graphic branch will expand on it. Just a suggestion :smile:

We could be able to do it in a separate branch or a separate fork, and later select it in by using a build flag.

**Comment by GothAck** [comment]
Hi, whilst yes I am writing an X server in JS, it is in no way feature complete, and is mostly a testing ground for ES6 / ES2016 features (with the goal of one-day making it feature complete). If you'd like to use it, you'll need a full v8 based browser (probably chromium) to get the benefit, which probably defeats the purpose :/

Any help with the x server would be appreciated though :P

**Comment by lite20** [comment]
>  you'll need a full v8 based browser (probably chromium) to get the benefit

I was intending on making a client + server styled renderer too, and then create X support. There are things about the x API that could be improved seeing that we're using nodejs. (Js makes everything better :laughing: )

> Any help with the x server would be appreciated though :P

I'll try to swing by and throw what I can!

> Do you have somewhere some info about that phone you've build?

At the moment, I haven't released anything on it. My little organization (hopefully to be a tech company some day) is contemplating how we want to release it. It's an incredible powerful phone, but we don't have the resources to mass manufacture and honestly I just want everyone to have a good phone once and for all.

I know someone with one of these :sob: .
![Nokia Flip Phone](http://welectronics.com/gsm/Nokia/nokia_6101.jpg)

I'll probably throw something about it on [the website](https://gfruit.info) eventually. It's only been running for a week :stuck_out_tongue: (not complete, but executable).

**Comment by lite20** [comment]
> Before wrong here: my node-canvas port is just only to paint on the screen from Node.js, it doesn't have anything about making CEF to run on it

Haha yes I'm aware!

> (CEF is the full Chromium, while we are interested only on the rendering engine), I think it should be mostly a matter of following this instructions to compile the embebed version with the DRM platform.

That sounds like a good plan. I'm curious to see how the canvas running on an HTML renderer would perform compared to a direct canvas port. I might write a "directC" (direct canvas :stuck_out_tongue:) mode for game developers who may potentially want a direct canvas. (if the game is full-screen, why go through all the work of rendering the browser when you can directly draw your rectangles?)

Feedback would be awesome!

**Comment by piranna** [comment]
> I'm curious to see how the canvas running on an HTML renderer would perform compared to a direct canvas port

Definitely worse, at least until we get hardware acceleration.


> I might write a "directC" (direct canvas :stuck_out_tongue:) mode for game developers who may potentially want a direct canvas. (if the game is full-screen, why go through all the work of rendering the browser when you can directly draw your rectangles?)

That's one of the reasons I ported node-canvas to NodeOS, just for games ;-)

**Comment by lite20** [comment]
I'm interested in using Node-canvas to do this. I'm exploring to find hardware acceleration methods but for the mean time, I believe I will begin developing the frame-buffer implementation using node-canvas and we will build off that. I'm having a bit of trouble getting node-canvas going. If you could hop on the IRC at some point, I'll be getting on in 30 minutes and it'd be great if I could throw my questions directly to you. Thanks!

> That's one of the reasons I ported node-canvas to NodeOS, just for games ;-)

Yes, that makes sense :stuck_out_tongue_closed_eyes:

**Comment by sidorares** [comment]
@lite20 https://github.com/luismreis/node-openvg-canvas is accelerated canvas library ( but not sure how specific to PI is it )

**Comment by lite20** [comment]
> @lite20 https://github.com/luismreis/node-openvg-canvas is accelerated canvas library ( but not sure how specific to PI is it )

Thanks! I'm going to see what I can make of it. Thanks!

**Comment by piranna** [comment]
> I'm interested in using Node-canvas to do this.

Do you **really** want to develop the GUI using node-canvas?!?! Hostly I don't believe it's a good idea...


> @lite20 https://github.com/luismreis/node-openvg-canvas is accelerated canvas library ( but not sure how specific to PI is it )

Fairly Pi-specific. node-openvg-canvas makes use of OpenVG libraries, that are specific for each graphic card, and although there are implementation for other ones not all of them have it. Also, having OpenVG working would be as difficult as having EGL working since they are somewhat related, and having EGL we could have accelerated Chromium :-) Baby steps better here ;-)

**Comment by lite20** [comment]
Do you really want to develop the GUI using node-canvas?!?! Hostly I don't believe it's a good idea...

My plan is to create a canvas implementation of sorts. Whether I use Node-canvas, or my own implementation (called BoxedBox).

BoxedBox is like Node-canvas except without Cairo. The part that Cairo handled, generating the buffers to  write to the frame buffer, I do from scratch. I directly bind the canvas commands to frame buffer implantations. For example when when you called to draw a square to the canvas, it'd draw it directly to the frame buffer instead (unless you specify that you want to call a refresh point).

If I used Node-canvas I would have to go through the stress of finding and implementing all these pixel rendering algorithms. However Node-canvas is fighting me right now and I'm having issues installing it so BoxedBox looks like the way to go. (BoxedBox is on my Bitbucket account, if you were looking for it)

**Comment by piranna** [comment]
> If I used Node-canvas I would have to go through the stress of finding and implementing all these pixel rendering algorithms

node-canvas offer the 2D context W3C canvas API, the same used on browsers. I don't find it difficult to use...


> If we implement BoxedBox now, we can easily swap it out for an updated faster EGL renderer in the future without users needing to update their code because it'd use the same interface.

The same happens with node-canvas, since Cairo has support for EGL.

**Comment by lite20** [comment]
> node-canvas offer the 2D context W3C canvas API, the same used on browsers. I don't find it difficult to use...

Sorry no I meant if I used BoxedBox I'd have to do that XD

**Comment by piranna** [comment]
> Then what are the downsides of using node-canvas?

Lower level API in comparation to a HTML renderer. node-canvas offer you only lines, dots & rectangles to paint with. For games or demos is good, for high level UIs it's better HTML and more compatible.

**Comment by lite20** [comment]
> For games or demos is good, for high level UIs it's better HTML and more compatible.

Ah okay, so you would like me to attempt to write a CEF (cef is easier to embed, than just blink, the renderer) implementation to render directly to frame buffer just as the canvas renderer. Sounds . I'll give it a shot.

**Comment by Risto-Stevcev** [comment]
I just noticed the NodeJS project a day or two ago, and I find this idea really interesting. My take on the GUI is that it should be using X11 and have support for Xvfb, even if it's a bit more work.

The reason being is that all modern linux systems (and some macs) use it, and so the way the browser graphics get rendered works as expected. A use-case for this OS is to have it run a CI environment, and in order to do E2E (integration) Webdriver testing, you want to be able to run your tests on browsers other than PhantomJS. The canonical way of doing this is to install Xvfb and run your tests 'headlessly' for Firefox or Chrome. To further debug your environment, you can get an X-server up and use the GUI for more in-depth debugging to see how/where your tests error out.

If something else gets used for a framebuffer or GUI client-server model, then it runs the risk of not rendering graphics exactly the way it would look on a modern Linux (or otherwise) system running modern browsers, which would make selenium tests harder to debug.

**Comment by piranna** [comment]
Hi Risto, and welcome. NodeOS is a server-oriented OS at least on its architecture and will not have a GUI on its core, but as you could see on this or other issues, the "official" (note the quotes) GUI architecture will be based on HTML5. NodeOS is Linux based so there's no a big hassle to run X11 on it, but we are not going to support it officially, in the mid-term the GUI will be used remotely from regular web browsers and in the long term it's planned to use a static build of Webkit or Gecko using directly EGL to remove intermediate layers like X11 and improve performance. Anyway, if you are interested on make NodeOS to run a X11 server we can help you and give you advice, I'm interested to know how far could it go :-)

**Comment by lite20** [comment]
> the "official" (note the quotes) GUI architecture will be based on HTML5.

"The Official, Unofficial Architecture :stuck_out_tongue: "

> If something else gets used for a framebuffer or GUI client-server model, then it runs the risk of not rendering graphics exactly the way it would look on a modern Linux (or otherwise) system running modern browsers, which would make selenium tests harder to debug.

All the rendering methods being experimented with in NodeOS at the moment are based around common rendering engines, like Webkit, CEF, and Blink. So the results of programs would be identical to rendering your app in for example firefox or Google Chrome ^_^ making design and implementation rather easy for developers as you don't even need a NodeOS system to develop NodeOS apps.

**Comment by lite20** [comment]
Closing due to a rejections of X, and progress on noGUI
