### ISSUE TITLE
Killing REPL Hangs NodeOS

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#180]
I don't believe this is intended behaviour, but after failing to navigate to userfs, I was greeted by a beautiful REPL terminal. (As a side node, maybe the user should be given multiple attempts?)

After killing the REPL with CTRl^C, (just for experimentation), NodeOS hangs for an indefinitely, completely unresponsive. Maybe killing the instance should be the cue to shut down the system? Potentially it could report the console log. If NodeOS (my apologies, I can't remember the name of the init script) has the tendency to crash then that might be a useful feature to implement.

Anyway, thought I'd point it out!

P.S. I used the init script in the latest ISO to launch QEMU

## Update ##
Could this be linked to issue https://github.com/NodeOS/NodeOS/issues/90 where killing REPL caused a kernel panic? Was a patch implemented so that it hangs the virtual machine instead? I did see a potential shutdown script mentioned. Maybe this is a great place to implement it :laughing:

**Comment by piranna** [comment]
> maybe the user should be given multiple attempts?

It should have given you several attempts... what was the name of the module that launched it (you can see it in the prompt when it gets showed).


> Maybe killing the instance should be the cue to shut down the system?

Probably :-) Not in barebones, since you get directly into the Node.js REPL, but maybe in another of the layers, and in fact currently it's being shown a message when the REPL gets closed. This could be done on the nodeos-mount-utils module by checking first that we are running as the PID 1 process, and on node-century by checking there's no more child processes. Pull-requests are welcome :-)


> Could this be linked to issue #90 where killing REPL caused a kernel panic?

Yes, it's talking about the same thing, only that about patching Node.js binary to close NodeOS also when running the barebones layer :-D

**Comment by piranna** [comment]
Fixed in master, clossing.
