### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#183]
## Forenote ##
I should probably mention that I'm completely aware of the beautiful wiki we have going on. This is referring to an official wiki site, as in `doc.nodeos.com` think of it as a users manu for users and/or developers.

## Actual Message ##
With our first official release, I believe it's time for us to begin the "daunting" task of documenting everything.

By documenting I mean creating a wiki of sorts that throughly explains the inner workings of NodeOS, and its systems. I've read countless times, how users often enjoy systems they can repair themselves. That might be a bit easier if you understand what you're tampering with. For new developers in the family such as I, it'd make contributing to the project not only easier, but effective.

I strongly believe that a lot of bugs occur simply for a misunderstanding of how something works. If you write a program with 80% of what you're working with, and someone else builds off with only 80% of your 80%, eventually there wont be much left. We'll have bugs tearing things apart and wont even know what program it's in.

Documentation is our next big step, and I know that throwing this out there will probably result in me spending hours and hours writing documentation pages. But I'm willing to do so, if y'all can clarify anything I might not understand fully.

The easiest way to do this would probably to base the documentation of a repository, and have the community make pull requests and push tweaks and additions. Then have some "documentation administration" accept or deny (with clarification of course) the pull requests.

Like I said, I'd be more than glad to lead this along. Although even after hours of tearing through code there are still things I don't yet understand (like which OS is NodeOS based off? Is NodeOS an LFS system? Why is NodeOS broken into four filesystems ;-; And why do we have multiple repositories for all these filesystems)

We are the future. Cheers!

P.S. the Github wiki is great. We might want to consider just building the entire thing off githuh if an official webpage is too much work.

**Comment by piranna** [comment]
> By documenting I mean creating a wiki of sorts that throughly explains the inner workings of NodeOS, and its systems.

Maybe we can have something similar to this when I finish my thesis bachelor, where I explain how NodeOS works and all the problems I got with it... :-D


> Documentation is our next big step, and I know that throwing this out there will probably result in me spending hours and hours writing documentation pages. But I'm willing to do so, if y'all can clarify anything I might not understand fully.

I find more important to get a 100% test coverage in all the modules and their dependencies, since some of them don't have tests due to developing it too fast. This can be done to improve documentation at the same time, too :-)


> Like I said, I'd be more than glad to lead this along.

You are more than welcome to do it :-)


> which OS is NodeOS based off? Is NodeOS an LFS system?

NodeOS is a Linux-based OS, taking some concepts from the [Cross Linux From Scratch Embedded](http://clfs.org/view/clfs-embedded) project, that's a derivation of Linux From Scratch focused on cross-compiled and embedded systems, but the modular and layered design of NodeOS makes it mostly kernel-agnostic and in the future is intended to be able to use several of them, including [runtime.js](http://runtimejs.org).


> Why is NodeOS broken into four filesystems ;-; And why do we have multiple repositories for all these filesystems

NodeOS is splitten in several bootable layers, being *barebones* with only the Linux kernel and the Node.js binary, *initramfs* that prepare the system to mount the users filesystem, and *usersfs* that give a multiuser system. This allow to organice better the system and make it more portable and easier to test.


> the Github wiki is great. We might want to consider just building the entire thing off githuh if an official webpage is too much work

It's ok for me to use it :-)

**Comment by lite20** [comment]
Alright, thanks for the reply! The explanations were super helpful. I'm excited for that thesis bachelor :stuck_out_tongue:.

I actually didn't know not all tests were covered. I'd lend a hand but I'm working a lot on BoxedBox. I'll remember to write tests for it too, and maybe throw a few in for simpler segments of NodeOS.

**Comment by piranna** [comment]
:+1:

**Comment by lite20** [comment]
> Maybe we can have something similar to this when I finish my thesis bachelor, where I explain how NodeOS works and all the problems I got with it... :-D

Still hyped! Would you like a specific system  testing or may I use mocha and expect JS?  Shall I place the tests in each modules respective repositories?

**Comment by piranna** [comment]
mocha is fine :-) And of course, the tests should be inside each respective project to make them autonomous... :-D I'll be waiting your pull-requests ;-)

**Comment by lite20** [comment]
> mocha is fine :-) And of course, the tests should be inside each respective project to make them autonomous... :-D I'll be waiting your pull-requests ;-)

Would you like tests for  the four filesystem's too? Here or on they're repod

**Comment by piranna** [comment]
What four filesystems? The four NodeOS layers? I would start doing the
tests on their dependencies first since they are already independent
modules...

**Comment by lite20** [comment]
@piranna ah okay. I'm on it. I'll be firing emails if there's things I don't understand in modules

**Comment by lite20** [comment]
How exactly does the NodeOS logon process work?

**Comment by lite20** [comment]
Closing as documentation is in progress ^_^
