### ISSUE TITLE
what makes nodeOS better than other OS ?

### ISSUE THREAD

**Issue by frankstein-1** [NodeOS/NodeOS#194]
Hi
I like the idea of this project, and I really want contribue on it.
After reading the introduction of the project. I didn't found the answer of the following question : 
what makes nodeOS different ? what can it do better than other existing OS ?
Best regards;

**Comment by lite20** [comment]
As you might know, NodeOS was born as an attempt to see if a NodeJs based operating system could be developed. If you've worked with NodeJs for a while you'll know that the JS language has some nice perks over other languages. One thing I particularly love about JS it's object oriented design. The way JS handles objects and how they can smoothly be altered interacted with and cloned makes it enjoyable to work with.

I guess the big thing about NodeOS is that it's... Well a NodeJS OS. Everyone sees a different image in NodeOS and like many JS based projects, NodeOS has so much potential. 

But I'm sure if you asked anyone else who's been here for some time, they can give an even better answer. Specifically @piranna

**Comment by evanplaice** [comment]
@frankstein-1 Two reasons.

General purpose operating systems are extremely complex. First they have to provide an extensive HAL (Hardware Abstraction Layer) that can support the wide range of different devices they can be installed on. Second, they need to provide functionality as well as protection for multiple users and many programs/services that support those users.

Web servers require none of that functionality. They generally run off of VMs (Virtual Machines) that abstract away all of the hardware-specific details and they're generally designed for single-purpose usage.

Lets say you decided to build an OS from scratch. Start by stripping everything down to the bare essentials. HAL isn't required because the VM already takes care of abstracting away the hardware. V8 already provides memory/filesystem sandboxing so the separation of user/kernel space (and all of the processing overhead it requires) is no longer necessary.

What you get is an OS that takes up less than 10MB of space, boots up in seconds, requires zero maintenance (other than pushing new updates), requires minimal memory overhead, and runs as fast or faster than the fastest C implementations running on a general purpose OS.

If you've ever used IaaS, you've probably had to deal with the pains of deployment. Deploying a complete general-purpose OS image is a PITA. Docker makes things easier by making it so you only have to deploy your application-specific differences but it adds yet another layer of abstraction, including more complexity and space/memory overhead. Plus, you still have to manage updating the underlying OS for security vulnerabilities and bug fixes.

Here are the layers of abstraction for a Docker deployment:

    Hardware -> VM -> Kernel Space -> User Space ->  Docker -> V8 VM -> Application

And for an application specific system in NodeOS:

    Hardware -> VM -> Kernel Space -> V8 VM -> Application

Fewer layers, means less bloat and drastically reduced surface area for security vulnerabilities.

-----

Use case - Building a Load Balancer:

1. clone NodeOS
2. install a load balancer implementation via NPM
3. install additional dependencies to auto-restart, log, profile the system
4. add a custom configuration

Run the build step which packages everything (incl a minimal Linux kernel and Node/V8) as a VM. Then deploy the VM using git or some other deployment tool.

Occasionally, you may need to update dependencies (npm update) and/or modify the config. Run the build step again and it's ready for deployment.

In most setups, the OS lives on the server and changes/updates are either managed remotely via provisioning tools (ex ansible/puppet) or pushed as Docker containers.

In a Unikernel. The setup, dependency management, build process can all be automated using NPM and existing libraries. The builds are small enough that they can be versioned using git.

Theoretically, you could do a whole system setup with 4 commands:
- git clone
- npm run install
- npm run build
- npm run deploy

**Comment by piranna** [comment]
@evanplaice, I'm going to cry, I wouldn't be able to write a better answer :'-) Would you be able to rewrite your answer as a new issue so I can be able to set it as an entry on the NodeOS blog? I would be able to copy the test myself, but if you open it then you would be shown as the author :-)

And as a personal note, can I be able to include your answer on my bachelor thesis? Of course I would reference you, but it's an almost perfect description of what NodeOS is and what can do... :-P

**Comment by evanplaice** [comment]
@piranna Haha. Thanks :+1: 

Of course I can add it as a new issue, and you're perfectly welcome to use it on your thesis. What do you think would make a good title for the post?

BTW, thanks for all your hard work on this project. I read through the issues and have been really impressed with the direction and specifically, your contribution to this project. I really hope I have an opportunity to use it in production in the future.

**Comment by lite20** [comment]
@evanplaice this is so 

> BTW, thanks for all your hard work on this project. I read through the issues and have been really impressed with the direction and specifically, your contribution to this project. I really hope I have an opportunity to use it in production in the future.

I second on this. You guide this so well, and keep everything well maintained it's remarkable. In a car, you're that battery keeping everything alive (and probably the engine too).

Thanks for all you do! We don't say thank you enough!

**Comment by evanplaice** [comment]
OK, I added my answer as a new issue. If you can think of a better title, let me know so I can change it.

**Comment by piranna** [comment]
> Of course I can add it as a new issue, and you're perfectly welcome to use it on your thesis.

Thank you ^^


> What do you think would make a good title for the post?

I've just fixed the title and published it.


> BTW, thanks for all your hard work on this project. I read through the issues and have been really impressed with the direction and specifically, your contribution to this project. I really hope I have an opportunity to use it in production in the future.

That would be cool :-) Yeah, I admit I have been a little bit obsesed with the project, but it's funny (at least when things goes on... :-P ). If this project lift up I hope someday someone could give me an employment to develop NodeOS so I could be able to have some spare time and have a life... :-P


> Thanks for all you do! We don't say thank you enough!

The best thank you are the pull-requests ;-)

**Comment by piranna** [comment]
Since @evanplaice has answer this so perfectly I'm going to close this issue :-)

**Comment by frankstein-1** [comment]
thanks for you all :+1:
