### ISSUE TITLE
Immutable Files

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#209]
Is NodeOS capable of flagging files as immutable as would be done with chattr on most linux distro's?

By immutable I'm referring to unalterable by anything. I was thinking about NodeOS security and the thought crossed my mind.

Does NodeOS being a Linux based distro have any file locking features exposed or can anyone and any program read and write anything on the system?

(Or recursively whipe your machine blank and leave you unbootable)

**Comment by piranna** [comment]
It has a vanilla linux kernel, so maybe it's only a matter of writting the programs :-) You have already the traditional UNIX file permissions, I don't know about that "inmutable" files but you can be able to remove the `write` permission making them read-only. Is that what you are asking about? Regarding wipe-out all the hard disk this is not possible since each user is isolated inside their own chroot jail with its own filesystem, if a user does a `rm -rf /` it will only remove it's $home files, the system or other users are untoched.

**Comment by lite20** [comment]
> Regarding wipe-out all the hard disk this is not possible since each user is isolated inside their own chroot jail with its own filesystem, if a user does a rm -rf / it will only remove it's $home files, the system or other users are untoched

Okay awesome! I didn't know.

> You have already the traditional UNIX file permissions, I don't know about that "inmutable" files but you can be able to remove the write permission making them read-only.

Ah okay excellent. From my research it was simply a file that couldn't be altered by anything. Not even accidentally editable by root. In order for it to be altered it had to first as root remove the flag.

Seeing as this ability is there its available to developers already so they should be free to use it.

**Comment by piranna** [comment]
> Ah okay excellent. From my research it was simply a file that couldn't be altered by anything. Not even accidentally editable by root. In order for it to be altered it had to first as root remove the flag.

Yeah, that can be done by disabling the `writable` file permission :-)

**Comment by lite20** [comment]
Awesome! Well with that, this is resolved. I'll remember to document this.

**Comment by piranna** [comment]
> I'll remember to document this.

Yeah please! Documentation is greatly needed :-P
