### ISSUE TITLE
Hit a REPL

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#251]
On the latest prebuild, I hit a REPL. The error provided is as so:

```
[    6.603843] overlayfs: upper fs needs to support d_type.
Trace: { [Error: EINVAL, Invalid argument 'overlay'] errno: 22, code: 'EINVAL', path: 'overlay', syscall: 'mount' }
    at onerror (/lib/node_modules/nodeos-mount-filesystems/server.js:37:13)
    at /lib/node_modules/nodeos-mount-filesystems/server.js:314:24
    at /lib/node_modules/nodeos-mount-filesystems/server.js:175:24
```

I had to retype that out by hand so I hope it's useful!

**Comment by piranna** [comment]
Uh-oh... what system are you using to run it? 32 bits or 64?

I got this recently on 32 bits (also on somewhat old prebuilds!!!) and seems to be related to an update on Linux kernel OverlayFS code, that now requires underlying read-write layer filesystem `stat()` function to support the `d_type` field without a fallback although it's only a dir listing time optimization... and almost nobody implements it, mostly only Ext2/3/4 when enabled the option :-( This could be a hue showstopper if it also start to happens on 64 bits, since NodeOS uses OverlayFS a lot combining several filesystem types... :-/ Honestly, when I read about it I got worried... :-(

**Comment by lite20** [comment]
I'm running Qemu x86_64 so that's 64bit. Time to run on bare-metal

**Comment by piranna** [comment]
http://www.spinics.net/lists/linux-fsdevel/msg94791.html

Here you have the culprit :-(

**Comment by lite20** [comment]
@piranna hm. Well, what do we do?

**Comment by piranna** [comment]
I'm not sure. We could go back to previous versions of Linux kernel to check if it gets fixed, but maybe the optimal solution would be to try to directly fix it. Until that, maybe we could try to work in other areas and improve tests so it doesn't happens again and we can get a quick notification of similar problems. Anyway, I'll try to get it a look (again... :-( ).

**Comment by piranna** [comment]
We have others things to work about, like the git client or noGui or noUpdate, so although we are not able to test it directly over NodeOS at this moment, we don't have a chance to get bored too ;-)

**Comment by piranna** [comment]
https://lkml.org/lkml/2016/5/16/23

Seems we are not alone... On the other hand, seems it would be fixed by enabling the usage of extended attributes when mounting the users partition, but this will need to be tested.

**Comment by lite20** [comment]
@piranna I guess we could give it a try. I'll see to finishing noUpdate now. Should we use the npm module or should we just issue commands ourselves?

**Comment by piranna** [comment]
It's better to use the npm module instead of launching commands.

**Comment by luii** [comment]
@piranna RC1 still has a repl error (same error described above)

**Comment by piranna** [comment]
Yeah, I know. Don't trust the mark RC1, I forgot to add it in november ;-)
When I finish the changes I'm doing and if we get to fix this, it will
became RC2.

**Comment by luii** [comment]
oh okay

**Comment by piranna** [comment]
What could you suggest to fix this? Seems is a Linux kernel issue... I'm
not sure if it will be fixed in the next major, there are some changes
about it, or maybe it could be fixed with a mount option...

**Comment by lite20** [comment]
> What could you suggest to fix this? Seems is a Linux kernel issue... I'm
not sure if it will be fixed in the next major, there are some changes
about it, or maybe it could be fixed with a mount option...

Potentially we could patch it? I can't say I understand the error 100% but if we're going the patch route I'd probably read a bit on it.

**Comment by piranna** [comment]
And... fixed! :-D

I found that the problem was introduced in [that kernel patch](https://patchwork.kernel.org/patch/8906821/), that checks the filesystem has support for `d_type` field, that's only available on Ext2/3/4 and Btrfs. This field improve performance by adding a field to store the filetype in the direntry and don't need to call `stat()` for each file, and it's used by OverlayFS to check the `whiteouts` (fake files added to the upper filesystem to mark the ones of the lower read-only one as deleted) and prevent to show them.

It seems that feature should be enabled by default, but the point is that the filesystem is being created with `genext2fs`, that as the name says it creates an Ext2 filesystem, so all the cool features (journaling, filetype...) needs to be enabled by hand. Just a [tune-up](https://github.com/NodeOS/nodeos-usersfs/commit/031f7967295a24650bbc8cb8dcee8c32479ca811) to the `nodeos-usersfs` module and now it's working again :-D I'll try to do some more tune-ups before generating a new nighly with it fixed ;-)

**Comment by lite20** [comment]
awesome! Closing for completion.

**Comment by piranna** [comment]
Cool ;-)

**Comment by kumarharsh** [comment]
@piranna I've been loosely following nodeOS development since it made the front-page on HN some time ago. Just stumbled upon it, and thought I might give it a go... But the docker image seems to be throwing this error:

```
mount procfs: Operation not permitted
mount devtmpfs: Operation not permitted
Trace: { Error: EPERM, Operation not permitted 'overlay'
    at Error (native) errno: 1, code: 'EPERM', path: 'overlay', syscall: 'mount' }
    at onerror (/lib/node_modules/nodeos-boot-multiUser/server.js:23:11)
    at /lib/node_modules/nodeos-boot-multiUser/server.js:46:26
    at /lib/node_modules/nodeos-boot-multiUser/lib/index.js:97:24
    at /lib/node_modules/nodeos-boot-multiUser/lib/jocker_root.js:198:24
Starting REPL session
NodeOS-boot-multiuser>
```

After which, as you can see, I'm put into a REPL session.

I'm running Windows Creators Update + Powershell on ConEMU.

**Comment by piranna** [comment]
The error says that the Linux kernel you are using (real or emulated) for your Docker image doesn't support OverlayFS, that's a fundamental part of NodeOS design.

**Comment by kumarharsh** [comment]
OK, but I don't understand what you mean by "... Linux kernel you are using for your Docker image...". I just installed using `docker run -t -i nodeos/nodeos`.
I'm assuming the linux kernel would be bundled with the nodeos image? I don't have any control over which kernel `docker run` gets, (I think)?

**Comment by piranna** [comment]
Docker works on top of LXC containers, that are a feature of Linux kernel. If the Linux kernel provided by your version of Docker don't support OverlayFS, then NodeOS will not run correctly. Probably in your case you would be more interested on using the QEmu images.

You say that you are using Windows, how are you executing your docker instance? A virtual machine, maybe?

**Comment by kumarharsh** [comment]
Yes, I'm using the Docker Toolbox which uses VirtualBox and the boot2docker distro. It might be that.

**Comment by piranna** [comment]
Then if `boot2docker` kernel don't support OverlayFS, your only alternative is to use QEmu images.

**Comment by kumarharsh** [comment]
I see. I'll do some digging on it.
