### ISSUE TITLE
v1.0.0-RC2.2016-06-24 partly faulty?

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#256]
I'd like to bring the lastest release v1.0.0-RC2.2016-06-24 into question.

Upon first running it, I noticed initramfs is gone, but assumed this was intentional. I first attempted to run it but it failed.

The run.sh packaged in this release attempts to run NodeOS with 'qemu-system-i386'. This will fail as QEMU complains that the kernel is 64 bit. To solve this, edit the run.sh to instead use 'qemu-system-x86_64'. 

I then ran again, and hit a new issue which isn't actually new. The 'dev/sdb2' cannot be found error. This can be bypassed by entering 'dev/sdb' into the prompt it provides.

After these tweaks, NodeOS will run as normal. It's debatable whether this release should be accepted, or if we ought to correct the qemu system typo in run.sh and then re-release.

As for dev/sdb2 not being found, I don't recall why that error occurred but it is somewhere amongst the dead threads.

**Comment by piranna** [comment]
I'm getting some problems to get RC2 to work due to all the architecture
changes. They are for the better of course, but didn't know there was so
much tiny bits to fix before due to it... :-/

**Comment by lite20** [comment]
Ah okay, completely alright. Is it possible to update the run.sh without having to compile the entire system again?

**Comment by lite20** [comment]
I'm assuming the breaking i386 wasn't intentional. Ought I go grab the error and create a thread?

**Comment by piranna** [comment]
Yes, it's not intentional. I'm trying to use prebuild for everything and
test each layer independently and this kind of things should not happen
again in the future, but it's not easy... :-P
El 24/6/2016 23:51, "Lite McFish" <notifications@github.com> escribió:

I'm assuming the breaking i386 wasn't intentional. Ought I go grab the
error and create a thread?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/NodeOS/NodeOS/issues/256#issuecomment-228470726>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAgfvutt9eo0riJTXCEVbibuvRrce8izks5qPFFJgaJpZM4I-JY2>
.

**Comment by lite20** [comment]
Closing as this has been discussed.

**Comment by piranna** [comment]
:+1: Also it should be already fixed in master.
