### ISSUE TITLE
Hack at a Prebuild

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#337]
Say I wanted to inject a .js file into my userfs. If I'm not mistaken, the prebuilds layers are ISO's. Can these ISO's be opened and tampered with using any form of program?

My use case is to inject compiled, static c programs like GCC or Mesa, along with my js scripts that use them in order to perform tests.

Ideally in the end said programs would be a part of the build process (Mesa likely a part of the graphic edition build process instead). Until this, however, is there any way for me to skip the compile time and hack on the prebuilds?

P.s. I think I was able to do it at one point but I forgot how I did. I'll mess more with it when I get back.

**Comment by piranna** [comment]
All layers now just generate plain tarfiles, being later converted to the platform specific format (for example, disk images). You could be able modify the tarfile and add your desired files, or fork the nodeos-usersfs repo and change the build script to add them. I have some changes pending for upload to be able to define the builder projects to use instead of the default ones, or also to be able to define directly the tarfiles to use if you want.

**Comment by lite20** [comment]
Awesome, thank you! I'll mess with this now that I have a chance. That solves the issue!

**Comment by piranna** [comment]
Cool ;-) If you need that I publish my changes give me a note :-)
