### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Varun-Sethu** [NodeOS/NodeOS#366]
Why did you choose Node.js?

**Comment by piranna** [comment]
can you explain your question?

**Comment by Varun-Sethu** [comment]
I'm just wondering why you decided to build an operating system in Node, I really like but but i'm just wondering why you chose JS over any other language.

**Comment by piranna** [comment]
Well, first of all the project was started by @groundwater, so probably he would give you a better answer :-) From my side, Node.js is well suited for async tasks as the ones that could happen on a regular OS, and also provides a high-level language that makes it easier to work on. The NodeOS concepts are fairly abstract, so they could be easily implemented using other languages too.

**Comment by Zayelion** [comment]
Its ecosystem and sheer number of developers. 

To explain it comically https://www.destroyallsoftware.com/talks/the-birth-and-death-of-javascript

**Comment by Varun-Sethu** [comment]
Cool!

**Comment by groundwater** [comment]
Hey. I'll jump into a quick answer.

1. It was an opportunity to learn about how Linux distributions worked
2. Every since node became mainstream, I have found it's great for systems programming. The combination of async, plus easy native code integration is fantastic.
3. Node keeps dependencies local. I have spent many _many_ hours wasted trying to get global package dependencies in debian/apt lined up. (Docker has more or less solved this problem)
4. As a challenge, I wanted to see how far I could get with nothing but node/npm on the system (i.e. calling libc directly vs shelling out). See some of my experiments [here](https://github.com/groundwater?utf8=%E2%9C%93&tab=repositories&q=node-src&type=&language=). Working with TTYS and setting network settings directly was particularly interesting.

In general I think booting an OS with node isn't any better or worse than booting it with a series of bash scripts. (If you're coming from a _systemd_ world, this may not be your experience anymore.)

This may or may not align with @piranna, but he effectively took over all vision, direction, and control of the project since 2014 (I think). I haven't touched the project in a while, but I love that it's continuing under a new direction.

**Comment by piranna** [comment]
> In general I think booting an OS with node isn't any better or worse than booting it with a series of bash scripts.

I think probably this is one of the best quotes to answer the question :-)

**Comment by shevegen** [comment]
> I think probably this is one of the best quotes to answer the question :-)

Well, that was in the old days. Now most distributsion have systemd.

Here is an example to work with ;)

[Unit]
Description=Postfix Mail Transport Agent
After=syslog.target network.target
Conflicts=sendmail.service exim.service

postifix.service taken from: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Unit_Files.html

[Service]
Type=forking
PIDFile=/var/spool/postfix/pid/master.pid
EnvironmentFile=-/etc/sysconfig/network
ExecStartPre=-/usr/libexec/postfix/aliasesdb
ExecStartPre=-/usr/libexec/postfix/chroot-update
ExecStart=/usr/sbin/postfix start
ExecReload=/usr/sbin/postfix reload
ExecStop=/usr/sbin/postfix stop

[Install]
WantedBy=multi-user.target

or https://unix.stackexchange.com/questions/348450/confused-by-execstartpre-entries-in-systemd-unit-file

[Unit]
Description=Startup Thing

[Service]
Type=oneshot
ExecStart=/usr/bin/python3 -u /opt/thing/doStartup
WorkingDirectory=/opt/thing
StandardOutput=journal
User=thingUser
# Make sure the /run/thing directory exists
PermissionsStartOnly=true
ExecStartPre=-/bin/mkdir -p /run/thing
ExecStartPre=/bin/chmod -R 777 /run/thing

[Install]
WantedBy=multi-user.target

**Comment by piranna** [comment]
> Well, that was in the old days. Now most distributsion have systemd.

Lol! X-D Yeah, I forgot the trojan horse in disguise :-P There are other distros that don't use SystemD and have moved to simpler init systems like rinit or minit. In fact, NodeOS use nodeos-init, one inspired on tini init binary. Yeah, probably it would be considered an advantage, specially now that I'm splitting and generalizing the internal NodeOS core to make it agnostic to Node.js...

**Comment by rolfen** [comment]
> In general I think booting an OS with node isn't any better or worse than booting it with a series of bash scripts. (If you're coming from a systemd world, this may not be your experience anymore.)

Surely JavaScript is more pleasant to work with then bash. PHP would be nicer too.
However that's one perspective. On the other hand, bash is older, smaller, more mature, hence arguably safer and more stable then node.

Okay, nowadays there is systemd and other init managers, which are much younger. However they were developed with the intent to be init managers, hence they should (I assume) have high stability standards.

Okay when you think about all the younger init managers, the argument for stability becomes less convincing.

I like working with node, however I would still not want it to run with root privilege on my system and be in charge of booting everything else.

Do you have any take on this aspect?

**Comment by piranna** [comment]
> I like working with node, however I would still not want it to run with root privilege on my system and be in charge of booting everything else.

Long time ago NodeOS don't exec Node.js code as system init, but instead [nodeos-init](https://github.com/piranna/nodeos-init). Regarding root priviledge, by design NodeOS just only use the root account to setup the system on boot process to allow a multiuser environment, when configured for single user enviroments there's no UID 0 processes besides `/init`.
