### ISSUE TITLE
Include text editor with standard distribution

### ISSUE THREAD

**Issue by secrettriangle** [NodeOS/NodeOS#66]
I think it would be a great idea if NodeOS came with a text editor. That would be one small but important step to having a fully functional, self-contained operating system. @groundwater and I spoke in #node-os on Freenode and he approves. There are two written in NodeJS that I know about: [hipster](https://github.com/dominictarr/hipster), and [slap](https://github.com/slap-editor/slap). Full disclosure, I am the author of slap, so I am biased, but I strongly believe every OS should at least have a text editor. :)

**Comment by piranna** [comment]
I've added Slap on the demo users filesystem, so I'll close this. There are problems with ```blessed``` related to terminfo, once a solution is found and they are fixed blessed-based apps will work fine.

**Comment by secrettriangle** [comment]
Sweet! How do I test this out? Is there a link to a commit or something?

**Comment by piranna** [comment]
I add it some commits ago and forgot about this issue, you can get it on master :-) As I said there are problems with blessed, latest ones should have a valid terminfo for Linux terminal based on Ubuntu linux-vt one so it should look fine in a QEmu window, but remotely on Terminator or gnome-terminal it shows a blank screen due to Unicode and control characters... :-/

**Comment by tylerl0706** [comment]
This looks great! How can I test this? Has this been added in?

**Comment by piranna** [comment]
> This looks great! How can I test this? Has this been added in?

Yes, slap is available inside the basic image :-)
